### ISSUE TITLE
Overflow issue in RxFlow.received/consumed?

### ISSUE THREAD

**Issue by fisx** [kazu-yamamoto/network-control#1]
Hi, I'm debugging http2 and ended up trying to wrap my head around the RxFlow interface, [for example](https://github.com/kazu-yamamoto/network-control/blob/main/Network/Control/Flow.hs#L86-L104).

From what I understand, `rxfConsumed` and `rxfReceived` accumulate all bytes over the lifetime of a stream, ie. `rxfReceived` is **not** decreased again by the consumed bytes after consumption.  Doesn't that mean when 2GB have gone over the stream, you get an overflow issue here?

Wouldn't it make more sense to keep track of the fill level of the buffer, ie. the value `rxfConsumed - rxfReceived`, instead?

Also I'm struggling to understand the comment above `maybeOpenRxWindow`.  I think `rxfWindow` is fixed over the lifetime of a stream, and `rxfLimit` is the space available for data that has been received but not yet consumed, is that correct?  Could it then be:

```
--   If `rxfLimit` is less than the half of `rxfWindow`,
--   limit is increased and the representation of window size update is returned.
```

Thanks, really appreciate your work @kazu-yamamoto!  :)

**Comment by kazu-yamamoto** [comment]
> From what I understand, `rxfConsumed` and `rxfReceived` accumulate all bytes over the lifetime of a stream, ie. `rxfReceived` is **not** decreased again by the consumed bytes after consumption.  Doesn't that mean when 2GB have gone over the stream, you get an overflow issue here?

I assume that `network-control` (and `quic`/`http2`) is used on 64bit CPUs.
So, the limitation is much larger.

> Wouldn't it make more sense to keep track of the fill level of the buffer, ie. the value `rxfConsumed - rxfReceived`, instead?

`network-control` is based on the spec of QUIC.
QUIC is newer than HTTP/2 which adopts your approach.
I guess that QUIC's approaches are safer than HTTP/2's approaches in general.
For instance, the concurrency limit for streams of HTTP/2 is known as vulnerable:
https://datatracker.ietf.org/doc/draft-thomson-httpbis-h2-stream-limits
So, I would like to go with QUIC's approaches anyway.

**Comment by kazu-yamamoto** [comment]
I'm very surprised because I don't expect other people read the code in this package.
I'm motivated, so I will try to improve documentation.

**Comment by kazu-yamamoto** [comment]
I hope that d1ca99d answers your questions.

**Comment by kazu-yamamoto** [comment]
The word "window" is confusing, I guess.
`rxfWindow` should be renamed to `rxfBufferSize`.

**Comment by fisx** [comment]
> So, I would like to go with QUIC's approaches anyway.

:+1: but then maybe change the type from `Int` to `Int64`?

**Comment by fisx** [comment]
> > So, I would like to go with QUIC's approaches anyway.
> 
> 👍 but then maybe change the type from `Int` to `Int64`?

oh, and maybe mention the RFC in the haddocs for `RxFlow`?  interesting read!

**Comment by fisx** [comment]
> I hope that [d1ca99d](https://github.com/kazu-yamamoto/network-control/commit/d1ca99d383690536b25d85354fd13469c0d50b9b) answers your questions.

yes, much clearer now, thanks!  but now i wonder why `rxfLimit` is even a record field and not a function `RxFlow -> Int`?  probably performance?

**Comment by fisx** [comment]
wait.  after reading https://datatracker.ietf.org/doc/draft-thomson-httpbis-h2-stream-limits/ more carefully, i'm confused again.  this is about concurrent stream limits, but `rxfLimit` etc are about limiting the total number of bytes sent over a connection.  How is the rfc relevant for my suggestion of maintaining a field `rxfConsumedMinusReceived` instead of the two separate fields, and make `rxfLimit` a function rather than a record field?

i should probably read more code, but maybe you can give me a hint?

**Comment by kazu-yamamoto** [comment]
> yes, much clearer now, thanks!  but now i wonder why `rxfLimit` is even a record field and not a function `RxFlow -> Int`?  probably performance?

I don't remember well but I guess my symmetry sense to `txfLimit`.

**Comment by kazu-yamamoto** [comment]
> wait.  after reading https://datatracker.ietf.org/doc/draft-thomson-httpbis-h2-stream-limits/ more carefully, i'm confused again.  this is about concurrent stream limits, but `rxfLimit` etc are about limiting the total number of bytes sent over a connection.  How is the rfc relevant for my suggestion of maintaining a field `rxfConsumedMinusReceived` instead of the two separate fields, and make `rxfLimit` a function rather than a record field?

My bad.
I did not understand that you are suggesting to remove the `rxfLimit` field.
Rather, I misunderstood that you suggest the diff approach of HTTP/2 instead of the total approach of QUIC.

I will consider `rxfLimit` again on next Monday.

**Comment by fisx** [comment]
> > wait.  after reading https://datatracker.ietf.org/doc/draft-thomson-httpbis-h2-stream-limits/ more carefully, i'm confused again.  this is about concurrent stream limits, but `rxfLimit` etc are about limiting the total number of bytes sent over a connection.  How is the rfc relevant for my suggestion of maintaining a field `rxfConsumedMinusReceived` instead of the two separate fields, and make `rxfLimit` a function rather than a record field?
> 
> My bad. I did not understand that you are suggesting to remove the `rxfLimit` field. Rather, I misunderstood that you suggest the diff approach of HTTP/2 instead of the total approach of QUIC.
> 
> I will consider `rxfLimit` again on next Monday.

no, you understood correctly.  i'm wrapping my head around things as we talk :)

you kinda talked me out of suggesting the diff approach of HTTP/2 by pointing me to the rfc.  then i took a closer look and realized i didn't understand the connection, but i trust you there is one.

tl;dr: we're on the same page now :) if you make rxfLimit a function i'll be happy, but i have no other change requests at this moment.

either way feel free to close this ticket.  thanks!

**Comment by kazu-yamamoto** [comment]
`rxfLimit == rxfConsumed + rxfWindow` does not stand *always* because `maybeOpenRxWindow` only modifies `rxfCosumed` not `rxfLimit` in the case of `otherwise`.

**Comment by kazu-yamamoto** [comment]
Closing.
I will make a new release soon.
